import type { Metadata } from "next";
import "./globals.css";
import { ClerkProvider } from '@clerk/nextjs'
import Provider from "./provider";
import { Outfit } from 'next/font/google'
import { Toaster } from "@/components/ui/sonner"
import { ColorModeProvider} from "./_context/ColorModeContext";

export const metadata: Metadata = {
  title: "ReelGenie",
  description: "Generated by create next app",
};

const outfit = Outfit({ subsets: ['latin'] })

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={outfit.className}
      >
        <ColorModeProvider>
        <ClerkProvider>
          <Provider>
            {children}
          </Provider>
          <Toaster />
        </ClerkProvider>
        </ColorModeProvider>
      </body>
    </html>
  );
}
