import type { Metadata } from "next";
import "./globals.css";
import { ClerkProvider } from '@clerk/nextjs'
import Provider from "./provider";
import { Outfit } from 'next/font/google'
import { Toaster } from "@/components/ui/sonner"

export const metadata: Metadata = {
  title: "AI-ShortVideoGen",
  description: "Generated by create next app",
};

const outfit = Outfit({ subsets: ['latin'] })

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={outfit.className}
      >
        <ClerkProvider>
          <Provider>
            {children}
          </Provider>
          <Toaster />
        </ClerkProvider>
      </body>
    </html>
  );
}
